### ISSUE TITLE
Partitioned cookie workaround likely needs to be changed to `(3, 14)`

### ISSUE THREAD

**Issue by bdraco** [uilibs/uiprotect#274]
https://github.com/uilibs/uiprotect/blob/1f8c024cc2abf40bb5ea74d297a76c4cedee40dc/src/uiprotect/api.py#L70C1-L76C1

Looks like https://github.com/python/cpython/pull/112714 didn't make it into 3.13

cc @ep1cman

**Comment by ep1cman** [comment]
I will look into this and see if I can come up with something more robust than relying on version numbers
