### ISSUE TITLE
Fingerprint & NFC event fired on Unifi Protect application reboot

### ISSUE THREAD

**Issue by EsposBjorne** [uilibs/uiprotect#311]
### Describe the bug

Updated my Home Assistant Core to 2024.12 to test the new NFC and Fingerprint events available in the unifi protect integration.

Added automation for fingerprint and nfc tag event for my g4 doorbell pro to open my yale doorman lock on successful scan with correct ID's following the examples in the documentation. The automation works great, but i noticed that after doing an update or restart off my Unifi Protect Application at unifi.ui.com, the NFC and Fingerprint events were fired with successful ID's.. This is not necessarily a Unifi Protect Hassio bug, but maybe it's more related to the actual Unifi Protect application at unifi.ui.com.. im not sure :) 

However, when restarting the unifi protect app, suddenly my yale doorman unlocked cause the fingerprint/nfc events actually contained the successful ID's for my finger and nfc tag causing my automation to trigger even while far away from home..
Again, i am not sure if this is related to the unifi protect application at unifi.ui.com or the unifi protect integration at hassio.

### To Reproduce

-Add fingerprint and/or NFC tag to G4 Doorbell Pro at Unifi Protect app at unifi.ui.com.
-Create automation to trigger on the 2 new events in the latest unifi protect hassio integration: NFC Card Scanned Event and Fingerprint Identified Event.
-Reboot or update unifi protect application at unifi.ui.com.
-Automation will trigger when application restarts and event data will contain ID's for both NFC tag and fingerprint. I only have 1 nfc tag and 1 finger added and both ID's was in the event data.

### Version

Home Assistant Core 2024.12.0. Operating system 14.0.

### Platform

Raspberry Pi 5 rpi5-64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by mattstocum** [comment]
I'm having the same issue. Was this closed because it's an issue in Home Assistant, or for some other reason?

**Comment by TheJulianJES** [comment]
See the link to the docs or the other workaround condition posted by me in https://github.com/home-assistant/core/issues/133241.
It's down to the implementation of HA (event) entities, not an issue with the uiprotect library.
