### ISSUE TITLE
Error: 'nfcCardScanned' is not a valid EventType

### ISSUE THREAD

**Issue by chrismcneil** [uilibs/uiprotect#332]
### Describe the bug

When scanning an NFC card on my G4 Doorbell Pro I get the following errors in home assistant
`2024-12-17 08:43:46.838 DEBUG (MainThread) [uiprotect.data.bootstrap] Validation error processing event: 67618012033d5803e40048a9. Ignoring event. Error: 'nfcCardScanned' is not a valid EventType
`

### To Reproduce

1. Configure https://www.home-assistant.io/integrations/unifiprotect in home assistant. HA version 2024.11.3
2. Configure an NFC card in Unifi Protect.
3. Scan card with debug logging enabled in home assistant.

### Version

6.4.0

### Platform

ghcr.io/home-assistant/home-assistant:2024.11.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by RaHehl** [comment]
How about switching to a Home Assistant version that actually supports this? 😉 https://www.home-assistant.io/blog/2024/12/04/release-202412/#noteworthy-improvements-to-existing-integrations

**Comment by chrismcneil** [comment]
Thanks I didn't see it in the release notes, I had to roll back to 2024.11.3 because of a bug in 2024.12. I'll try again once the other bug is fixed.

**Comment by RaHehl** [comment]
Out of curiosity, which bug?

**Comment by chrismcneil** [comment]
This issue is causing my server to boot loop.
https://github.com/NabuCasa/hass-nabucasa/issues/761
https://github.com/home-assistant/core/issues/132586
