### ISSUE TITLE
global recording settings

### ISSUE THREAD

**Issue by bdraco** [uilibs/uiprotect#35]
### Describe the bug

It seems that protect 4.0 has removed all the global recording settings.

At some point in the future, once most people have updated to 4.x, we should strip them all out since 

### To Reproduce

n/a

### Version

1.0.0

### Platform

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### No Duplicate

- [X] I have checked existing issues to avoid duplicates.

**Comment by TheJulianJES** [comment]
I think the cameras can still have the "global" option enabled in Protect 4.x if the settings weren't changed on that version.
If that's the case, any changes to the camera from the library might fail until the global option is disabled.

**Comment by bdraco** [comment]
It looks like its still in bootstrap so might just be removed from the frontend.
Probably going to be a wait and see thing

**Comment by bdraco** [comment]
Looks like its going to stay this way at least for a while
